# Generated by Django 4.1 on 2022-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studenttempschoolreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentpermanentschoolreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolnumber', models.PositiveBigIntegerField()),
                ('classname', models.CharField(max_length=50)),
                ('studentid', models.PositiveBigIntegerField()),
            ],
        ),
    ]
