# Generated by Django 4.1 on 2022-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentpermanentschoolreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.PositiveBigIntegerField()),
                ('schoolid', models.PositiveBigIntegerField()),
                ('passingdate', models.DateField(auto_now_add=True, null=True)),
                ('studentclass', models.CharField(max_length=50)),
                ('studentpercentage', models.PositiveBigIntegerField()),
            ],
        ),
    ]
