# Generated by Django 4.1 on 2022-10-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hod',
            new_name='hods',
        ),
    ]
