# Generated by Django 4.1 on 2022-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0002_rename_hod_hods'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=8)),
                ('adhar', models.PositiveBigIntegerField()),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('dob', models.DateField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
