# Generated by Django 4.1 on 2022-11-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffhist',
            fields=[
                ('staffemail', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('studentid', models.PositiveBigIntegerField()),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
