# Generated by Django 4.1 on 2022-11-13 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0004_staffhist'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffhist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffhist',
            name='staffemail',
            field=models.CharField(max_length=30),
        ),
    ]
