# Generated by Django 4.1 on 2022-11-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0006_alter_staffhist_staffemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffhist',
            name='remark',
            field=models.CharField(max_length=500),
        ),
    ]
