# Generated by Django 4.1 on 2022-11-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0007_alter_staffhist_remark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staffhist',
            new_name='staffhistory',
        ),
    ]
