# Generated by Django 4.1 on 2022-11-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0008_rename_staffhist_staffhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staffhistory',
            new_name='staffhist',
        ),
    ]
