# Generated by Django 4.1 on 2022-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0009_rename_staffhistory_staffhist'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffhistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffemail', models.CharField(max_length=30, null=True)),
                ('studentid', models.PositiveBigIntegerField()),
                ('remark', models.CharField(max_length=500)),
            ],
        ),
    ]
