# Generated by Django 4.1 on 2022-11-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0010_staffhistories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staffhist',
        ),
    ]
