# Generated by Django 4.1 on 2022-11-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0011_delete_staffhist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staffhistories',
        ),
    ]
